letter_extraction/db/urls.py
from django.urls import path
from . import views

app_name = 'db'
urlpatterns = [
    #path('', views.index, name='index'),
    path('index/', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('upload/', views.upload, name='upload'),
    path('result/', views.search_result, name='result'),
    path('edit/<int:items>/', views.edit, name='edit'),
    path('edit/', views.edit, name='edit'),
    path('login/', views.login_user, name='login'),
    path('upload/scanfile/', views.upload, name='scanfile'),
    path('logout/', views.logout, name='logout'),
    path('labels/', views.labels, name='labels'),
    path('drag_n_drop_test/', views.drag_n_drop_test, name='drag_n_drop_test'),
]

letter_extraction/letter_extraction/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    #path('', include('db.urls')),
    path('db/', include('db.urls')),
    path('admin/', admin.site.urls),
]

letter_extraction/db/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User
# Create your models here.
from django.db.models import CharField


class Person(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    full_name = models.CharField(max_length=100)
    date_added = models.DateTimeField('date added')
    date_modified = models.DateTimeField('date modified')

    def __str__(self):
        return self.full_name


class Location(models.Model):
    place_name = models.CharField(max_length=128, default = "Unknown")
    date_added = models.DateTimeField('date added')
    date_modified = models.DateTimeField('date modified')

    def __str__(self):
        return str(self.place_name)


class PersonLocation(models.Model): # this is just a table to denote a many-to-many relationship between Persons and Locations
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)


class Document(models.Model):
    archive_number = models.CharField(max_length=300)
    date_written = models.CharField(max_length=150)
    receiver = models.ForeignKey(PersonLocation, related_name='receiver', on_delete=models.CASCADE)
    sender = models.ForeignKey(PersonLocation, related_name='sender', on_delete=models.CASCADE)
    document_type = models.CharField(max_length=16)
    language = models.CharField(max_length=64)
    date_added = models.DateTimeField('date added', null=True, default=None)
    date_modified = models.DateTimeField('date modified')
    uploaded_by = models.ForeignKey(User, on_delete=models.CASCADE)
    notes = models.CharField(max_length = 10000)

    def __str__(self):
        return str(self.archive_number)

class Privileges(models.Model):

    class Meta:

        managed = False

        permissions = (
            ('can_upload', 'User has the ability to upload a document.'),
            ('can_search', 'User has the ability to search for documents.'),
            ('can_edit', 'User has the ability to edit document data.'),
        )

# feel free to add more fields. To add these to the database, use python(3) manage.py makemigrations; and then python(3) manage.py migrate

letter_extraction/db/forms.py
from django import forms
from .models import *
from django.db.models import Q

class documentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = (#'archive_number', 
        'date_written', 'document_type', 'language')

    def save_form(self):
        if self.is_valid():
            document = self.save()
            document.save()
            return True


class personLocationForm(forms.ModelForm):
    class Meta:
        model = PersonLocation
        fields = '__all__'

    def save_form(self):
        if self.is_valid():
            person_location = self.save()
            person_location.save()
            return True


class personForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ['first_name', 'last_name', 'full_name']

    def save_form(self):
        if self.is_valid():
            person = self.save()
            person.save()
            return True

class locationForm(forms.ModelForm):
    class Meta:
        model = Location
        fields = ['place_name']

    def save_form(self):
        if self.is_valid():
            location = self.save()
            location.save()
            return True


def get_forms_by_document(request, id):
    forms = []
    document = Document.objects.filter(pk=id).first()
    sender_pl = PersonLocation.objects.filter(pk=document.sender.pk).first()
    receiver_pl = PersonLocation.objects.filter(pk=document.sender.pk).first()
    sender_person = Person.objects.filter(pk=sender_pl.person.pk).first()
    sender_location = Location.objects.filter(pk=sender_pl.location.pk).first()
    receiver_person = Person.objects.filter(pk=receiver_pl.person.pk).first()
    receiver_location = Location.objects.filter(pk=receiver_pl.location.pk).first()

    document_form_post = documentForm(request.POST, instance=document)
    forms.append(document_form_post)
    document_form = documentForm(instance=document)
    forms.append(document_form)
    sender_form = personForm(instance=sender_person)
    forms.append(sender_form)
    receiver_form = personForm(instance=receiver_person)
    forms.append(receiver_form)
    sender_location_form = locationForm(instance=sender_location)
    forms.append(sender_location_form)
    receiver_location_form = locationForm(instance=receiver_location)
    forms.append(receiver_location_form)

    return forms

letter_extraction/db/views.py
import datetime
from django.template import loader
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login
from .forms import *
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect, render_to_response
from django.contrib.auth.decorators import login_required, permission_required
from django.db.models import Q
from db.services import query_service, account_service, upload_service, store_service,  results_service, model_service
from .models import *

#Testing import python function

# Create your views here.

from django.template import RequestContext

result = {}
indicator = 0
archive_number_list = []
previous_url = ""

@login_required
def index(request):
    context = {'myflag':'False'}
    if request.method == "POST":
        global result
        global indicator
        global archive_number_list
        store_service.deleteReplicates(archive_number_list)
        if indicator == 0:
            try:
                store_service.addToModel(result, request.user)
                context = {'myflag':'True'}
            except:
                errmsg = 'Storing of letters were not successful! Contact administrator for further details!'
                return render(request,'db/upload.html',{'err': errmsg, 'errtype': 'store'})
        elif indicator == 1:
            try:
                store_service.addToModel_xlsx(result, request.user)
                context = {'myflag':'True'}
            except:
                errmsg = 'Storing of letters were not successful! Contact administrator for further details!'
                indicator = 0
                return render(request,'db/upload.html',{'err': errmsg, 'errtype': 'store'})
            indicator = 0
    result = {}
    archive_number_list = []
    return render(request, 'db/index.html', context)


@login_required
def search(request):
    if not request.user.has_perm('db.can_search'):
        return render(request, 'db/index.html', {"message":"You do not have the permissions to perform this task!"})
    template = loader.get_template('db/search.html')
    header = ['Archive Number', 'Date Written', 'Document Type', 'Language', 'Place Written', 'Sender Name', 'Place Received', 'Receiver Name']
    values = query_service.analyze_query_request("", "", True, request.user)
    context = {'header': header, 'values':values}
    return HttpResponse(template.render(context, request))

    # search by archive numbers, use that to get some document
    # docs.obj.filter - you can find on djjango doc
    # should be a list of documents
    # feed it into return_doc ([], the doc shit)


@login_required
def search_result(request):
    global previous_url
    previous_url = ""
    if not request.user.has_perm('db.can_search'):
        return render(request, 'db/index.html', {"message":"You do not have the permissions to perform this task!"})
    search_type = str(request.GET['searchtype'])
    query_value = str(request.GET['query'])
    values = query_service.analyze_query_request(search_type, query_value, False, request.user)
    header = ['Archive Number', 'Date Written', 'Document Type', 'Language', 'Place Written', 'Sender Name', 'Place Received', 'Receiver Name', 'Edit']
    #primary_keys = query_service.get_pks(values)
    context = {'header': header, 'values': values}
    return render(request, 'db/result.html', context)


@login_required
def upload(request):
    if not request.user.has_perm('db.can_upload'):
        return render(request, 'db/index.html', {"message":"You do not have the permissions to perform this task!"})
    if request.method == "POST" and  request.FILES.get('myfile',False):
        if ((not request.FILES['myfile'].name.endswith('.xlsx')) and (not request.FILES['myfile'].name.endswith('.xls')) and (not request.FILES['myfile'].name.endswith('.docx'))):
            return render(request,'db/upload.html',{"fname":request.FILES['myfile'].name})
        global indicator
        global result
        global archive_number_list
        result, errmsg = upload_service.main(request.FILES['myfile'])
        results_service.archive_number_finder(result, archive_number_list) #checking for duplicates, duplicate archive numbers will be stored in archive_number_list
        indicator = 0 #docx files
        if (request.FILES['myfile'].name.endswith('.xlsx') or request.FILES['myfile'].name.endswith('.xls')):
            indicator = 1 #xlsx and xls files
        return render(request,'db/upload.html',{"list":result, "indic": indicator, "fname": request.FILES['myfile'].name, 'err': errmsg, 'errtype': 'preview'})
    else:
        template = loader.get_template('db/upload.html')
        context = {}
    return render(request,'db/upload.html',context)

@login_required
def edit(request, items):
    if not request.user.has_perm('db.can_edit'):
        return render(request, 'db/index.html', {"message":"You do not have the permissions to perform this task!"})
    forms = get_forms_by_document(request, items)
    context = {}
    if request.method == "POST":
        if forms[0].is_valid():
            instance = forms[0].save(commit=False)
            instance.save()
            context["update_message"] = 'Successfully updated!'
            return render(request, 'db/edit.html', context)
        else:
            context["update_message"] = 'Update failed!'
            return render(request, 'db/edit.html', context)   
    context = {
        'document_form' : forms[1],
        'sender_form' : forms[2],
        'receiver_form' : forms[3],
        'sender_location_form' : forms[4],
        'receiver_location_form' : forms[5],
        }
    return render(request, 'db/edit.html', context)


def login_user(request):
    message = None
    if request.method=="POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            if account_service.login_user(request):
                return redirect('db:index')
        else:
            context = {'form':AuthenticationForm(), 'message':'Username or password incorrect!'}
    else:
        context =  {'form':AuthenticationForm(), 'message':message}
    return render(request, 'db/login.html', context)


def logout(request):
    account_service.logout_user(request)
    return redirect('db:login')

def drag_n_drop_test(request):
    context = {}
    return render(request, 'db/drag_n_drop_test.html', context)

@login_required
def labels(request):
    if not request.user.has_perm('db.can_edit'):
        return render(request, 'db/index.html', {"message":"You do not have the permissions to perform this task!"})
    if 'new_label' in request.GET:
        model_service.add_metadata_label(request.GET['new_label'])
    labels = model_service.get_metadata_labels()
    context = {'labels':labels}
    return render(request, 'db/labels.html', context)

letter_extraction/db/templates/db/drag_n_drop_test.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <link rel="stylesheet" href="{% static 'db/styles.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open Sans|Tangerine|Inconsolata">
    <link rel="icon" type="image/png" href="{% static 'db/favicon-b.png' %}">
    {% block head %}
    <title></title>
    {% endblock %}
</head>
<body>
    <div class="header">
        <img style="width:2.4rem; float:left; margin-left: 0.7rem; margin-right: 0.3rem; margin-top: 0.45rem;" src="{% static 'db/favicon-b.png' %}">
        <a href="{% url 'db:index' %}" class="logo">Historical Archive Search</a>
        {% block hr %}
        <div class="header-right">
            <!--<a class="active" href="{% url 'db:index' %}">Home</a>-->
            <a href="{% url 'db:index' %}">Home</a>
            <a href="{% url 'db:search' %}">Search</a>
            <a href="{% url 'db:upload' %}">Upload</a>
            <a href="{% url 'db:logout' %}" id="logout">Logout</a>
        </div>

        {% endblock %}
    </div>
    <div class="main">
    {% block body %}
        <h1>Under Construction!</h1>
    {% endblock %}
    </div>

    <div class="footer">
      © A/Prof John Kinder; Mr Francesco De Toni; UWA 2018
    </div>

</body>

</html>

letter_extraction/db/templates/db/edit.html
{% extends 'base.html' %}
{% load static %}

<title>Letter Search - Upload</title>

<div class="main">

    {% block hr %}
    <script src="{% static "db/script.js" %}"></script>
    <div class="header-right">
        <a href="{% url 'db:index' %}">Home</a>
        <a href="{% url 'db:search' %}">Search</a>
        <a class="active">Edit</a>
        <a href="{% url 'db:upload' %}">Upload</a>
        <a href="{% url 'db:labels' %}">Metadata</a>
        <a onclick="return logout();" id="logout">Logout</a>
    </div>
    {% endblock %}



    {% block body %}
    <div class="main">
        {% if update_message %}
            <h3>{{update_message}}</h3>
        {% endif %}
        {% if document_form %}
            <h2>Edit result with archive number: {{document_form.archive_number.value}}</h2>
            <p><strong>Warning: </strong> For safety reasons, you may not change a document's 
                archive number!</p>
                <h3>Author Information</h3>
                Name of author: {{sender_form.full_name.value}} <br>
                Location of author: {{sender_location_form.place_name.value}} <br>
                <h3>Receiver Information</h3>
                Name of receiver: {{receiver_form.full_name.value}} <br>
                Location of receiver: {{receiver_location_form.place_name.value}} <br>

            <p style="color:darkblue;">Note that the editing of persons and locations
                is not yet functional.
            </p>
            <form method = "POST" action = "">
                <h3>Document</h3>
                {% for f in document_form %}
                    <p>{{f.label}}:{{f}}</p>
                {% endfor %}
                {% csrf_token %}
                <div class="download-button">
                    <button class="bt-submit" type="submit">Save</button>
                </div>
            </form>
        {% endif %}
        <div class="download-button">
            <button class="bt-discard" id="back-to-results" onclick="window.history.back()">Back</button>
        </div>
    </div>
    {% endblock %}

letter_extraction/db/templates/db/index.html
{% extends 'base.html' %}

    {% load static %}
    {% block head %}
    <title>Letter Search - Home</title>
    {% endblock %}

    {% block hr %}
    <script src="{% static "db/script.js" %}"></script>
    <div class="header-right">
        <a class="active" href="{% url 'db:index' %}">Home</a>
        <a href="{% url 'db:search' %}">Search</a>
        <a href="{% url 'db:upload' %}">Upload</a>
        <a href="{% url 'db:labels' %}">Metadata</a>
        <a onclick="return logout();" id="logout">Logout</a>
    </div>
    {% endblock %}

    {% block body %}
    <div class="main">
        {% if message %}
          <h2 style="color: red">{{message}}</h2>
        {% endif %}

        <h1>Welcome To The Digital Missionary Archive!</h1><br>

      <h2> The Search Button!</h2>
      <p> Clicking the 'Search' button at the top right of the page will take you to a page in which
        you can search the historical archive database directly. To use the search
        page, select the metadata categories which are relevant to your search and
        type in the information you want. You will then be redirected to a results
        page.
      </p>


      <h2> The Upload Button!</h2>
      <p> Clicking the 'Upload' button at the top right of the page will take you to our upload page in which you can
        add valuable metadata to our ever growing database. On this page click the
        choose file button and navigate to your desired word or excel document.
        Our application will then scan your document for metadata. You will get a
        chance to confirm this is the correct metadata you wish to upload.
        If there are any further questions please contact: Francesco.detoni@research.uwa.edu.au 
      </p>

      <h2>Data Policy</h2>
      <p style="margin-top:0">This website has been designed to never store the actual document transcripts on a server for any longer than a brief moment of time. When the file is uploaded, its information is passed on to a program which extracts the meta-data. Despite the file being uploaded to our server, it is never actually stored; its information is only extracted.</p>


      <script>
        // Confirmation message that data from latest upload has been successfully stored
        var success = '{{myflag}}';
        if (success == 'True'){
          alert('Data from the latest preview are successfully stored!');
        }
      </script>


    {% endblock %}

letter_extraction/db/templates/db/labels.html
{% extends 'base.html' %}

{% load static %}
{% block head %}
<title>Letter Search - Home</title>
{% endblock %}

{% block hr %}
<script src="{% static "db/script.js" %}"></script>
<div class="header-right">
    <a href="{% url 'db:index' %}">Home</a>
    <a href="{% url 'db:search' %}">Search</a>
    <a href="{% url 'db:upload' %}">Upload</a>
    <a class="active" href="{% url 'db:labels' %}">Metadata</a>
    <a onclick="return logout();" id="logout">Logout</a>
</div>
{% endblock %}

{% block body %}
<div class="main">
    
    <h2>Currently the following metadata labels exist for historical documents:</h2>
    {% if labels %}
        <select style="font-family: inherit" name="Click HERE">
            <option selected>Click to see metadata labels</option>
            {% for l in labels %}
                <option>{{l}}</option>>
            {% endfor %}
        </select>
    {% endif %}
    <h3>If you wish to add a metadata category, type the name of this category below:</h3>
    <br>
    <form method="GET" action="{% url 'db:labels' %}">
        <input type="text" name="new_label" required><br><br>
        <input type="submit" class="submitform" value="Add">
    </form>
</div>
{% endblock %}

letter_extraction/db/templates/db/login.html
{% extends 'base.html' %}

    {% block head %}
    <title>Letter Search - Login</title>
    {% endblock %}

    {% block hr %}
    <div class="header-right">
        <a href="{% url 'db:index' %}">Home</a>
        <a href="{% url 'db:search' %}">Search</a>
        <a href="{% url 'db:upload' %}">Upload</a>
        <a href="{% url 'db:labels' %}">Metadata</a>
    </div>
    {% endblock %}

    {% block body %}
    <div class="main">
    <h1>Login</h1>
    <form method="POST"  action="{% url 'db:login' %}" id="form1">
        {% csrf_token %}

        <div class="select">
        {{ form }}
        </div>
        <br>
        <br>
        <input class="submitform" type="submit" value="Login" form="form1">
        <br>
        <div style="font-size:10px">
            <i>Don't have an account? Request for an account to this e-mail: Francesco.detoni@research.uwa.edu.au</i>
        </div>
    </form>
    <br>
    {% if message %}
        {{message}}
    {% endif%}

    {% endblock %}

  </div>

letter_extraction/db/templates/db/result.html
{% extends 'base.html' %}

{% load static %}
{% block head %}
<title>Letter Search - Results</title>
{% endblock %}

{% block hr %}
<script src="{% static "db/script.js" %}"></script>
<script src="{% static "db/csv_controller.js" %}"></script>
<div class="header-right">
    <a href="{% url 'db:index' %}">Home</a>
    <a class="active" href="{% url 'db:search' %}">Search</a>
    <a href="{% url 'db:upload' %}">Upload</a>
    <a href="{% url 'db:labels' %}">Metadata</a>
    <a onclick="return logout()" id="logout">Logout</a>
</div>
{% endblock %}

{% block body %}

<div class="main">
    <!--{% if values %}
      <button class="bt-download" onclick="to_csv()">Download as CSV</button>
      {% endif %}-->
    {% if values %}
    <h2>{{values|length}} results found.</h2>
    <div class="preview-results">
    <table id="results_table" class="results_table">
        {% if header %}
        <tr>
            {% for h in header %}
            <th>{{h}}</th>
            {% endfor %}
        </tr>
        {% endif %}
        {% if values %}
            {% for value in values %}
            <tr>
                {% for v in value %}
                    {% if forloop.counter0 == 8 %}
                        <td>
                            <a href="/db/edit/{{v}}/">Modify</a>
                        </td>
                    {% else %}
                        <td>{{v}}</td>
                    {% endif %}
                {% endfor %}
            </tr>
            {% endfor %}
        {% endif %}
    </table>
  </div>
    {% else %}
        <h2>0 results found.</h2>
    {% endif %}
    <!-- <div class="footer"> -->
        <div class="download-button">
            <button class="bt-discard" onclick="backToSearch()">Back To Search</button>
            <button class="bt-upload" onclick="sortTable()">Sort By Archive Number</button>
            <button class="bt-download" onclick="toCsv()">Download as CSV</button>
        </div>
        <br>
    <!-- </div> -->
    {% endblock %}
</div>

letter_extraction/db/templates/db/search.html
{% extends 'base.html' %}

    {% load static %}
    {% block head %}
    <title>Letter Search - Search</title>
    {% endblock %}


    {% block hr %}
    <script src="{% static "db/script.js" %}"></script>
    <div class="header-right">
        <a href="{% url 'db:index' %}">Home</a>
        <a class="active" href="{% url 'db:search' %}">Search</a>
        <a href="{% url 'db:upload' %}">Upload</a>
        <a href="{% url 'db:labels' %}">Metadata</a>
        <a onclick="return logout()" id="logout">Logout</a>
    </div>
    {% endblock %}

    {% block body %}
    <div class="main">
    <h1>Search through our database! </h1>

    <p>You can search our database directly by typing in some query words.
    <br>
    <p><strong>Archive Numbers: </strong> A standard search will return all archive numbers that <i>contain</i> your search query. If you
    wish to only return the <i>exact</i> result, enclose the search query in double quotes. <b>Note</b> that this is only for archive numbers.
    <p><strong>Persons and places:</strong> If your search string is <span style="font-family: Inconsolata">query, query::author</span> 
    and <span style="font-family: Inconsolata"> query::receiver</span>
    filter your query string depending on if it refers to the author or the receiver. 
    Leaving off the modifier will result in unfiltered results.</p> 
    <p>
    <strong>Dates:</strong>
    If you wish to search for a year range, type <span style="font-family: Inconsolata">year1-year2</span>
    into the search bar.
    </p>
    <p> Search by: </p>

    <form method="GET"  action="{% url 'db:result' %}" id="form1">
        <div class="select">
            <input type="radio" name="searchtype" value="document" form="form1" required>Archive Number
            <input type="radio" name="searchtype" value="person" form="form1">Person
            <input type="radio" name="searchtype" value="location" form="form1">Place
            <input type="radio" name="searchtype" value="date" form="form1">Year
            <input type="radio" name="searchtype" value="document_type" form="form1">Document Type
            <input type="radio" name="searchtype" value="language" form="form1">Language
        </div>
        <br>
        <input type="text" name="query" placeholder="Search..." class="searchbar" form="form1" required>
        <br>
        <br>
        <input class="submitform" type="submit" value="Search" form="form1">
    </form>
</div>

<div class="main" style="min-height:300px;background-color:rgb(250, 250, 250);">
    <h2>Not sure what to search for?</h2>
    <p>Try searching for one of the fields from the database preview below.</p>
          {% if values %}
          <div class="preview-results">
          <table id="results_table" class="results_table">
              {% if header %}
              <tr>
                  {% for h in header %}
                  <th>{{h}}</th>
                  {% endfor %}
              </tr>
              {% endif %}
              {% if values %}
              {% for value in values %}
              <tr>
                  {% for v in value %}
                    {% if forloop.counter0 != 8 %}
                        <td>{{v}}</td>
                    {% endif %}
                  {% endfor %}
              </tr>
              {% endfor %}
              {% endif %}
          </table>
        </div>
          {% else %}
          <p>No results.</p>
          {% endif %}
</div>
</div>

{% endblock %}

letter_extraction/db/templates/db/simple_upload.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <link rel="stylesheet" href="{% static 'db/styles.css' %}">
    <title>Letter Search - Home</title>
</head>
<body>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>

  {% if uploaded_file_url %}
    <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
  {% endif %}

  <p><a href="{% url 'home' %}">Return to home</a></p>
{% endblock %}
</body>
</html>

letter_extraction/db/templates/db/test.html
{% extends 'base.html' %}

<title>Letter Search - Upload</title>

<div class="main">

    {% block hr %}
    <div class="header-right">
        <a href="{% url 'db:index' %}">Home</a>
        <a href="{% url 'db:search' %}">Search</a>
        <a class="active" href="{% url 'db:upload' %}">Upload</a>
        <a href="{% url 'db:logout' %}">Logout</a>
    </div>
    {% endblock %}



      {% block body %}
        {% if document_test_form %}
          <form method = "POST" action = "">
            {{document_test_form}}
            {{person_test_form}}
            {{location_test_form}}
              {% csrf_token %}
              <input type = "submit" value = "Save">
          </form>
          {% else %}
              <p>No results.</p>
          {% endif %}

        {% endblock %}
      </div>